services:
  server:
    image: "barumel/docker-astroneer-server:latest"
    environment:
      - "ASTRO_SERVER_PUBLIC_IP=${ASTRO_SERVER_PUBLIC_IP}"
      - "ASTRO_SERVER_DOMAIN_NAME=${ASTRO_SERVER_DOMAIN_NAME}"
      - "ASTRO_SERVER_PORT=${ASTRO_SERVER_PORT:-8777}"
      - "ASTRO_SERVER_NAME=${ASTRO_SERVER_NAME}"
      - "ASTRO_SERVER_PASSWORD=${ASTRO_SERVER_PASSWORD}"
      - "ASTRO_SERVER_OWNER_NAME=${ASTRO_SERVER_OWNER_NAME}"
    ports:
      - ${ASTRO_SERVER_PORT:-8777}:${ASTRO_SERVER_PORT:-8777}/tcp
      - ${ASTRO_SERVER_PORT:-8777}:${ASTRO_SERVER_PORT:-8777}/udp
    restart: unless-stopped
    volumes:
     - astroneer:/astroneer
     - steamcmd:/steamcmd
     - backup:/backup

volumes:
  astroneer:
  steamcmd:
  backup:
